version: '3.8'

services:
  api:
    build:
      context: ./python plots api/apiproject
    ports:
      - "5000:5000"
    volumes:
      - ./python plots api/apiproject:/app
    environment:
      FLASK_ENV: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 3s
      retries: 10
      start_period: 10s
      timeout: 10s

  mock-backend:
    build:
      context: ./python plots api/mockbackend
    volumes:
      - ./python plots api/mockbackend:/app
    depends_on:
      api:
        condition: service_healthy  


  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: welcometothedb
    ports:
      - "3306:3306"
