version: '3.8'

services:
  app:
    build:
      context: .          # Use the current directory for the Dockerfile
      dockerfile: Dockerfile
    container_name: symfony-app
    ports:
      - "8000:8000"       # Map port 8000 on the host to port 8000 in the container
    volumes:
    - .:/app
    - type: tmpfs
      target: /app/var
    environment:
      - APP_ENV=prod       # Set Symfony environment (dev/prod)
    stdin_open: true       # Keep stdin open for Symfony CLI interaction (optional)
    tty: true              # Allocate a pseudo-TTY for Symfony CLI (optional)
